java_test(
    name = "TreeObjectTest",
    size = "small",
    srcs = [
        "TreeObjectTest.java",
    ],
    deps = [
        "//src/main/java/net/ajmichael/gat/objects",
        "@truth//jar",
    ],
)
