java_library(
    name = "objects",
    srcs = [
        "BlobObject.java",
        "CommitObject.java",
        "GitObject.java",
        "TreeObject.java",
    ],
    visibility = ["//visibility:public"],
)