package(default_visibility = ["//visibility:public"])

java_library(
    name = "objects",
    srcs = [
        "BlobObject.java",
        "GitObject.java",
        "Mode.java",
        "commit/CommitObject.java",
        "tree/TreeEntry.java",
        "tree/TreeObject.java",
    ],
    deps = [
        "@guava//jar",
    ],
)
