java_library(
    name = "commands",
    srcs = [
        "Command.java",
        "CommandsModule.java",
        "HashObject.java",
    ],
    deps = [
        "//third_party:dagger",
        "@guava//jar",
    ],
    visibility = ["//visibility:public"],
)
